sudo: true
language: bash
services:
  - docker
os:
  - linux
stages:
  - Linting
  - Synthesis
  - Simulation
jobs:
  include:
    - stage: Linting
      script: make docker lint
    - stage: Synthesis
      script: make docker all
    - stage: Simulation
      script: make docker simulate-file 