sudo: true
language: bash
os:
  - linux

addons:
  apt:
    packages:
      - clang
      - libffi-dev
      - mercurial
      - graphviz
      - xdot
      - libftdi-dev
      - gperf

before_install:
  - PROJECT_PATH=$(pwd)

install:
  - sudo ./scripts/installtools.sh

script:
  - cd $PROJECT_PATH
  - make clean lint all simulate-file